// === Modular ===

// Ndef
// Ndef Parameter
// NdefMixer (auch: ProxyMixer)
// Setzen von Ndef Parametern, Mapping von Parametern
// Ndef Audio Routing

// === Triggers ===

// PulseDivider, Stepper, PulseCount, ...
// Select, ...
// => Kann in der Übung zu 'Demand' noch ausgeweitet werden

// === Feedback ===

// Aus technischer Sicht relevant:
// InFeedback
// LocalIn/LocalOut

// Praktisch: Feedback Quark

// Feedback mit Ndef